name: Test Build with Bun

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies with Bun
        run: bun install

      - name: Build the project
        run: bun run build

      - name: On Success Action
        if: success()
        run: echo "Build and tests were successful. Proceeding with additional actions."

      - name: Send API Request
        if: success() # Only runs if the build step is successful
        env:
          API_URL: https://course-scheduler-zeta.vercel.app/api
        run: |
          response=$(curl -X GET "$API_URL" -w "%{http_code}" -o /dev/null)
          if [ "$response" -ne 200 ]; then
            echo "API request failed with status code $response"
            exit 1
          else
            echo "API request was successful"
          fi

